version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: catwalk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'train'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017-27019:27017-27019
    volumes:
      - mongo-data:/var/lib/mongo

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
    postgres-data:
      external: true
    mysql-data:
      external: true
    mongo-data:
      external: true